### ISSUE TITLE
Update minetest to 5.10.0

### ISSUE THREAD

**Issue by farribeiro** [ronoaldo/minetestserver#26]
A new version is ready

I am requesting this due to I am facing server connections error. I believe version 5.9.0 is bugged

**Comment by farribeiro** [comment]
Note: the executable has changed name

**Comment by farribeiro** [comment]
I understand that the task list is not in this project

**Comment by ronoaldo** [comment]
I "overcomplicated" the setup, so I'll have to re-build this image first. Thanks for the heads up! Soon I'll also update the Mercurio build.

**Comment by adrinux** [comment]
Oof. Not just the executable renamed. Seems like most of the COPY  commands in the build second stage fail because things are in a different location.

**Comment by ronoaldo** [comment]
@adrinux yep! I managed to build the client side app in .AppImage format. I'll try again to make the container work and perhaps add some symlinks to help making the transition easier.

**Comment by adrinux** [comment]
I can't easily provide a patch now I'm using my own Dockerfile based on yours, too much deviation, but here are the needed COPY paths that I changed with `MINETEST_VERSION` set to 5.10.0

```bash
COPY --from=builder /usr/share/doc/luanti/minetest.conf.example /etc/minetest/minetest.conf
COPY --from=builder /usr/share/luanti /usr/share/luanti
COPY --from=builder /usr/src/minetest/games /usr/share/luanti/games
COPY --from=builder /usr/bin/luantiserver /usr/bin
# Copy the symlink too
COPY --from=builder /usr/bin/minetestserver /usr/bin
```

There is already a symlink from minetestserver to luantiserver (presumably added by the install script) so I added a copy command for that too, to keep compatibility with your minetest-wrapper.sh script.

Also had to modify the WORKDIR for contentdb to get mods installed in the correct path.

```bash
# Install mods from ContentDB
WORKDIR /usr/share/luanti
```

Hope this provides some help.

**Comment by ronoaldo** [comment]
Thank you so much! This is very helpful.

**Comment by adrinux** [comment]
I should also have mentioned I found a really useful docker/podman feature for multi-stage builds, you can [target a named build stage](https://docs.docker.com/build/building/multi-stage/#stop-at-a-specific-build-stage) for the image. So I was able to build only the "builder" stage and examine the state of the image filesystem. It felt like the easiest way to find where the Luanti install script was putting everything.

From the directory containing the Dockerfile and creating an image called "luanti-fiveten":

```bash
docker build --target builder -t luanti-fiveten .
```

For Podman the command is the same, just replace 'docker' with 'podman'.

**Comment by ronoaldo** [comment]
I'm considering to adopt the naming changes from upstream in this project, except for the repo name as of now.

That means changing the name of the wrapper script as well as the name of the container image.

Running a local test build with the changes to make sure it all works properly.

**Comment by ronoaldo** [comment]
CI building and testing is running. Thanks again for the help @adrinux!
